# estimate the pose of target objects detected
import numpy as np
import json
import os
import ast
import cv2
from YOLO.detector import Detector


# list of target fruits and vegs types 

TARGET_TYPES = ['orange', 'lemon', 'pear', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']

#TODO function to strip the colour aspect of the label before processing in target pose estimation 

def normalise_label(label):

    base_labels = ['orange', 'lemon', 'pear', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']

    for base in base_labels:
        if label.startswith(base):
            return base
        
    return label

def estimate_pose(camera_matrix, obj_info, robot_pose):
    """
    function:
        estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
    input:
        camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
            |f_x, s,   c_x|
            |0,   f_y, c_y|
            |0,   0,   1  |
            (f_x, f_y): focal length in pixels
            (c_x, c_y): optical centre in pixels
            s: skew coefficient (should be 0 for PenguinPi)
        obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
        robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
    output:
        target_pose: dict, prediction of target pose
    """
    # read in camera matrix (from camera calibration results)
    focal_length = camera_matrix[0][0]

    # there are 8 possible types of fruits and vegs
    ######### Replace with your codes #########


    target_dimensions_dict = {'orange': [0.0756, 0.0767, 0.0729], 'lemon': [0.054,0.074, 0.0536], 
                              'pear': [0.0704, 0.07565, 0.10425], 'tomato': [0.0678, 0.07, 0.0617], 
                              'capsicum': [0.07487, 0.07447, 0.0931], 'potato': [0.0677, 0.094, 0.0566], 
                              'pumpkin_orange': [0.08475, 0.08225, 0.07815], 'garlic': [0.0578, 0.0645, 0.0747],
                              'apple': [0.0678, 0.07, 0.0617], 'capsicum_green': [0.07487, 0.07447, 0.0931],
                              'capsicum_yellow': [0.07487, 0.07447, 0.0931], 'pear_yellow' : [0.0704, 0.07565, 0.10425],
                              'pear_green' : [0.0704, 0.07565, 0.10425], 'capsicum_red': [0.07487, 0.07447, 0.0931],
                              'pumpkin_green': [0.08475, 0.08225, 0.09515]}
    #########

    # estimate target pose using bounding box and robot pose
    target_class = obj_info[0]     # get predicted target label of the box
    target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
    true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label

    # compute pose of the target based on bounding box info, true object height, and robot's pose
    pixel_height = target_box[3]
    pixel_center = target_box[0]
    distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
    # training image size 320x240p
    image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
    x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
    theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
    ang = theta + robot_pose[2]     # angle of object in the world frame
    
   # relative object location
    distance_obj = distance/np.cos(theta) # relative distance between robot and object
    x_relative = distance_obj * np.cos(theta) # relative x pose
    y_relative = distance_obj * np.sin(theta) # relative y pose
    relative_pose = {'x': x_relative, 'y': y_relative}
    #print(f'relative_pose: {relative_pose}')

    # location of object in the world frame using rotation matrix
    delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
    delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
    # add robot pose with delta target pose
    target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
                   'x': (robot_pose[0]+delta_x_world)[0]}
    

    print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
    print(f'target_pose: {target_pose}')

    # TODO - adding offset for cube centres for 2d pictures of fruit 
 
    offset_distance = 0.055 # 4 cm in meters

    # Compute direction from robot to target - chat gpt 
    dx = target_pose['x'] - robot_pose[0][0]
    dy = target_pose['y'] - robot_pose[1][0]
    norm = np.sqrt(dx**2 + dy**2)
    if norm > 0:
        dx_offset = offset_distance * dx / norm
        dy_offset = offset_distance * dy / norm
        target_pose['x'] += dx_offset
        target_pose['y'] += dy_offset


    return target_pose


def merge_estimations(target_pose_dict, distance_threshold=0.10):
    """
    Merge multiple sightings of the same class if their (x,y) are within
    'distance_threshold' meters. The merged pose is the centroid of the cluster.

    input:
        target_pose_dict: dict like { "orange_0": {"x": ..., "y": ...}, ... }
    output:
        target_est: flat dict like { "orange_0": {"x": ..., "y": ...}, "orange_1": ... }
    """
    # 1) group detections by base class name (ignore trailing index)
    grouped = {}
    for key, pose in target_pose_dict.items():
        base = key.split("_")[0]  # "orange_3" -> "orange"
        grouped.setdefault(base, []).append({"x": float(pose["x"]), "y": float(pose["y"])})

    # 2) cluster per class by centroid distance
    #    each cluster keeps running sums to compute centroid robustly
    class_clusters = {}  # { "orange": [ {"sumx":..., "sumy":..., "n":..., "cx":..., "cy":...}, ... ] }
    for cls, poses in grouped.items():
        clusters = []
        for p in poses:
            px, py = p["x"], p["y"]
            placed = False

            # try to place into an existing cluster (compare to current centroid)
            for c in clusters:
                cx, cy = c["cx"], c["cy"]
                dist = np.hypot(px - cx, py - cy)
                if dist <= distance_threshold:
                    # merge into cluster and update centroid
                    c["sumx"] += px
                    c["sumy"] += py
                    c["n"] += 1
                    c["cx"] = c["sumx"] / c["n"]
                    c["cy"] = c["sumy"] / c["n"]
                    placed = True
                    break

            # if not close to any existing cluster, start a new one
            if not placed:
                clusters.append({
                    "sumx": px, "sumy": py, "n": 1,
                    "cx": px, "cy": py
                })

        class_clusters[cls] = clusters

    # 3) flatten back to desired output format with enumerated indices
    target_est = {}
    for cls, clusters in class_clusters.items():
        # stable ordering: left-to-right, then bottom-to-top (optional but nice)
        clusters_sorted = sorted(clusters, key=lambda c: (c["cx"], c["cy"]))
        for i, c in enumerate(clusters_sorted):
            target_est[f"{cls}_{i}"] = {"y": c["cy"], "x": c["cx"]}

    return target_est



# main loop
if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)

    # read in camera matrix
    fileK = f'{script_dir}/calibration/param/intrinsic.txt'
    camera_matrix = np.loadtxt(fileK, delimiter=',')

    # init YOLO model
    model_path = f'{script_dir}/YOLO/model/best.pt'
    yolo = Detector(model_path)

    # create a dictionary of all the saved images with their corresponding robot pose
    image_poses = {}
    with open(f'{script_dir}/lab_output/images.txt') as fp:
        for line in fp.readlines():
            pose_dict = ast.literal_eval(line)
            image_poses[pose_dict['imgfname']] = pose_dict['pose']

    # estimate pose of targets in each image
    target_pose_dict = {}
    detected_type_list = []
    for image_path in image_poses.keys():
        input_image = cv2.imread(image_path)
        bounding_boxes, bbox_img = yolo.detect_single_image(input_image)
        # cv2.imshow('bbox', bbox_img)
        # cv2.waitKey(0)
        robot_pose = image_poses[image_path]

        for detection in bounding_boxes:

            #TODO add in the label normalisation for labels
            normalised_label = normalise_label(detection[0])

            # count the occurrence of each target type - using normalised labels 
            occurrence = detected_type_list.count(normalised_label)

            # use normalised label for pose estimateion
            target_pose_dict[f'{normalised_label}_{occurrence}'] = estimate_pose(camera_matrix, detection, robot_pose)

            detected_type_list.append(normalised_label)

    # merge the estimations of the targets so that there are at most 3 estimations of each target type
    target_est = {}
    target_est = merge_estimations(target_pose_dict)
    # print(target_est)



    # TODO to test out the normalisation print out the detected type list 
    # print(detected_type_list)

    # After you have your target pose estimations in a dict (e.g., target_est)
# Each key should be like "orange_0", "pumpkin_1", etc., and value should be a dict with "x" and "y"

# If your detections are grouped by type and index, flatten them:


    # save target pose estimations
    with open(f'{script_dir}/lab_output/targets.txt', 'w') as fo:
        json.dump(target_est, fo, indent=4) # just to see if out code is wrong 
        

    print('Estimations saved!')
